"""create users table

Revision ID: 2458eee4686d
Revises: c9e199790fb7
Create Date: 2025-11-09 19:41:07.587055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2458eee4686d'
down_revision: Union[str, Sequence[str], None] = 'c9e199790fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.execute("UPDATE users SET password_hash = 'TEMP_HASH' WHERE password_hash IS NULL;")
    op.alter_column('users', 'password_hash', nullable=False)
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', name='roleenum'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
